spring:
  application:
    name: api-gateway
  http:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

server:
  port: 9010

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
