spring:
  application:
    name: console
  http:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

server:
  port: 8888
  context-path: /api

feign:
  product:
    url:  http://main-data:8801
  catalog:
    url: http://main-data:8801
  image:
    url: http://main-data:8801
  user:
    url: http://main-data:8801
  member:
    url: http://member:8803

