apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-entry
spec:
  rules:
  - host: laoking.auction.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: backend
          servicePort: 8701