spring:
  application:
    name: console

server:
  port: 8888
  context-path: /api

feign:
  product:
    url:  http://main-data:8801/product
  catalog:
    url: http://main-data:8801/catalog
  image:
    url: http://main-data:8801/image
  user:
    url: http://main-data:8801/user

